import { Product } from './types';

export const LANGUAGES = [
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
];

export const TRANSLATIONS: { [key: string]: { [lang: string]: string } } = {
  heroTitle: {
    pt: 'Café da manhã na cama LX',
    en: 'Breakfast in Bed LX',
    es: 'Desayuno en la cama LX',
    fr: 'Petit-déjeuner au lit LX',
    de: 'Frühstück im Bett LX',
    it: 'Colazione a letto LX',
  },
  heroSubtitle: {
    pt: 'O conforto de um pequeno-almoço português artesanal entregue diretamente na sua porta.',
    en: 'The comfort of an artisanal Portuguese breakfast delivered directly to your doorstep.',
    es: 'La comodidad de un desayuno portugués artesanal entregado directamente en su puerta.',
    fr: 'Le confort d’un authentique petit-déjeuner portugais artisanal livré directement à votre porte.',
    de: 'Der Komfort eines handgemachten portugiesischen Frühstücks, direkt an Ihre Tür geliefert.',
    it: 'La comodità di una colazione artigianale portoghese consegnata direttamente alla tua porta.',
  },
  bookNow: {
    pt: 'Reservar Agora',
    en: 'Book Now',
    es: 'Reservar Ahora',
    fr: 'Réserver Maintenant',
    de: 'Jetzt Buchen',
    it: 'Prenota Ora',
  },
  viewMenus: {
    pt: 'Ver Menus',
    en: 'View Menus',
    es: 'Ver Menús',
    fr: 'Voir les Menus',
    de: 'Menüs Ansehen',
    it: 'Vedi i Menu',
  },
  whyUs: {
    pt: 'Porquê Nós',
    en: 'Why Us',
    es: '¿Por qué nosotros?',
    fr: 'Pourquoi Nous',
    de: 'Warum Wir',
    it: 'Perché Sceglierci',
  },
  whyUsSubtitle: {
    pt: 'Uma experiência gastronómica luxuosa e sem esforço, pensada para enriquecer a sua estadia em Lisboa.',
    en: 'A luxurious and effortless gastronomic experience designed to enrich your stay in Lisbon.',
    es: 'Una experiencia gastronómica lujosa y sin esfuerzo diseñada para enriquecer su estancia en Lisboa.',
    fr: 'Une expérience gastronomique luxueuse et sans effort conçue pour enrichir votre séjour à Lisbonne.',
    de: 'Ein luxuriöses und müheloses gastronomisches Erlebnis, das Ihren Aufenthalt in Lissabon bereichert.',
    it: 'Un’esperienza gastronomica lussuosa e senza sforzo pensata per arricchire il tuo soggiorno a Lisbona.',
  },
  promotions: {
    pt: 'Ofertas Exclusivas',
    en: 'Exclusive Offers',
    es: 'Ofertas Exclusivas',
    fr: 'Offres Exclusives',
    de: 'Exklusive Angebote',
    it: 'Offerte Esclusive',
  },
  store: {
    pt: 'A Nossa Loja',
    en: 'Our Store',
    es: 'Nuestra Tienda',
    fr: 'Notre Boutique',
    de: 'Unser Shop',
    it: 'La Nostra Boutique',
  },
  cart: {
    pt: 'Carrinho',
    en: 'Cart',
    es: 'Carrito',
    fr: 'Panier',
    de: 'Warenkorb',
    it: 'Carrello',
  },
  wishlist: {
    pt: 'Favoritos',
    en: 'Favorites',
    es: 'Favoritos',
    fr: 'Favoris',
    de: 'Favoriten',
    it: 'Preferiti',
  },
  searchPlaceholder: {
    pt: 'Procurar menus ou extras...',
    en: 'Search menus or extras...',
    es: 'Buscar menús o extras...',
    fr: 'Rechercher des menus ou extras...',
    de: 'Menüs oder Extras suchen...',
    it: 'Cerca menu o extra...',
  },
  categories: {
    pt: 'Categorias',
    en: 'Categories',
    es: 'Categorías',
    fr: 'Catégories',
    de: 'Kategorien',
    it: 'Categorie',
  },
  all: {
    pt: 'Todos',
    en: 'All',
    es: 'Todos',
    fr: 'Tous',
    de: 'Alle',
    it: 'Tutti',
  },
  menus: {
    pt: 'Menus Principais',
    en: 'Main Menus',
    es: 'Menús Principales',
    fr: 'Menus Principaux',
    de: 'Hauptmenüs',
    it: 'Menu Principali',
  },
  extras: {
    pt: 'Extras',
    en: 'Extras',
    es: 'Extras',
    fr: 'Suppléments',
    de: 'Extras',
    it: 'Extra',
  },
  rulesWarning: {
    pt: 'Os extras só podem ser adquiridos juntamente com um menu principal.',
    en: 'Extras can only be purchased together with a main menu.',
    es: 'Los extras solo se pueden comprar junto con un menú principal.',
    fr: 'Les suppléments ne peuvent être achetés qu’avec un menu principal.',
    de: 'Extras können nur zusammen mit einem Hauptmenü erworben werden.',
    it: 'Gli extra possono essere acquistati solo insieme a un menu principale.',
  },
  ruleBlockText: {
    pt: 'Adicione pelo menos um menu principal para comprar extras.',
    en: 'Add at least one main menu to purchase extras.',
    es: 'Agregue al menos un menú principal para comprar extras.',
    fr: 'Ajoutez au moins un menu principal pour acheter des suppléments.',
    de: 'Fügen Sie mindestens ein Hauptmenü hinzu, um Extras zu kaufen.',
    it: 'Aggiungi almeno un menu principale per acquistare gli extra.',
  },
  reserveCalendar: {
    pt: 'Detalhes da Reserva',
    en: 'Reservation Details',
    es: 'Detalles de Reserva',
    fr: 'Détails de la Réservation',
    de: 'Reservierungsdetails',
    it: 'Dettagli della Prenotazione',
  },
  deliveryZones: {
    pt: 'Áreas de Entrega',
    en: 'Delivery Areas',
    es: 'Áreas de Entrega',
    fr: 'Zones de Livraison',
    de: 'Liefergebiete',
    it: 'Zone di Consegna',
  },
  deliveryZonesSubtitle: {
    pt: 'Entregamos em vários bairros históricos de Lisboa com toda a discrição e pontualidade.',
    en: 'We deliver to several historic Lisbon neighborhoods with absolute discretion and punctuality.',
    es: 'Entregamos en varios barrios históricos de Lisboa con total discreción y puntualidad.',
    fr: 'Nous livrons dans plusieurs quartiers historiques de Lisbonne en toute discrétion et ponctualité.',
    de: 'Wir liefern absolut diskret und pünktlich in verschiedene historische Viertel von Lissabon.',
    it: 'Consegniamo in diversi quartieri storici di Lisbona con la massima discrezione e puntualità.',
  },
  checkout: {
    pt: 'Finalizar Pedido',
    en: 'Checkout',
    es: 'Finalizar Pedido',
    fr: 'Passer la Commande',
    de: 'Kasse',
    it: 'Cassa',
  },
  clientAccount: {
    pt: 'Conta Cliente',
    en: 'Client Account',
    es: 'Cuenta de Cliente',
    fr: 'Compte Client',
    de: 'Kundenkonto',
    it: 'Area Clienti',
  },
  orderDeadlineNotice: {
    pt: 'As encomendas para o dia seguinte devem ser feitas até às 23:00.',
    en: 'Orders for the next day must be placed by 11:00 PM.',
    es: 'Los pedidos para el día siguiente deben realizarse antes de las 23:00.',
    fr: 'Les commandes pour le lendemain doivent être passées avant 23h00.',
    de: 'Bestellungen für den nächsten Tag müssen bis 23:00 Uhr aufgegeben werden.',
    it: 'Gli ordini per il giorno successivo devono essere effettuati entro le 23:00.',
  },
};

export const PRODUCTS: Product[] = [
  {
    id: 'menu-vitamin-c',
    name: {
      pt: 'Menu Vitamina C',
      en: 'Vitamin C Menu',
      es: 'Menú Vitamina C',
      fr: 'Menu Vitamine C',
      de: 'Vitamin C Menü',
      it: 'Menu Vitamina C',
    },
    category: 'menu',
    price: 10.90,
    contents: {
      pt: ['Sumo de laranja natural fresco', 'Torta de laranja caseira', 'Quiche de cogumelos selvagens', 'Croissants recheados com queijo cottage e kiwi'],
      en: ['Fresh squeezed orange juice', 'Homemade orange roll cake', 'Wild mushroom quiche', 'Croissants filled with cottage cheese and kiwi'],
      es: ['Zumo de naranja natural fresco', 'Torta de naranja casera', 'Quiche de champiñones silvestres', 'Croissants rellenos de queso cottage y kiwi'],
      fr: ['Jus d’orange pressé frais', 'Gâteau roulé à l’orange maison', 'Quiche aux champignons sauvages', 'Croissants garnis de fromage cottage et kiwi'],
      de: ['Frisch gepresster Orangensaft', 'Hausgemachter Orangenschneckenkuchen', 'Quiche mit wilden Pilzen', 'Croissants gefüllt mit Hüttenkäse und Kiwi'],
      it: ['Spremuta d’arancia fresca', 'Torta all’arancia fatta in casa', 'Quiche di funghi selvatici', 'Croissant ripieni di ricotta e kiwi'],
    },
    image: '/src/assets/images/vitamina_c_menu_1784378715670.jpg',
    description: {
      pt: 'Uma explosão refrescante de vitalidade e frescura para começar o seu dia em Lisboa. Uma combinação perfeita entre doces cítricos e um toque salgado de cogumelos.',
      en: 'A refreshing burst of vitality and freshness to start your day in Lisbon. A perfect balance of sweet citrus and savory mushroom quiche.',
      es: 'Una refrescante explosión de vitalidad y frescura para comenzar su día en Lisboa. El equilibrio perfecto entre el dulce cítrico y el quiche salado de champiñones.',
      fr: 'Une explosion rafraîchissante de vitalité et de fraîcheur pour commencer la journée à Lisbonne. Un équilibre parfait entre agrumes doux et quiche salée.',
      de: 'Ein erfrischender Stoß von Vitalität und Frische, um Ihren Tag in Lissabon zu beginnen. Eine perfekte Balance zwischen süßen Zitrusnoten und herzhafter Pilzquiche.',
      it: 'Un’esplosione rinfrescante di vitalità e freschezza per iniziare la giornata a Lisbona. Un perfetto equilibrio tra la dolcezza degli agrumi e la quiche ai funghi.',
    },
    ingredients: {
      pt: 'Laranjas do Algarve, farinha de trigo artesanal, cogumelos locais frescos, ovos biológicos, queijo cottage cremoso, kiwis frescos, manteiga biológica.',
      en: 'Algarve oranges, artisanal wheat flour, local wild mushrooms, organic eggs, creamy cottage cheese, fresh kiwi, organic butter.',
      es: 'Naranjas del Algarve, harina de trigo artesanal, champiñones locales frescos, huevos orgánicos, queso cottage cremoso, kiwis frescos, mantequilla orgánica.',
      fr: 'Oranges de l’Algarve, farine de blé artisanale, champignons sauvages locaux, œufs bio, fromage cottage crémeux, kiwis frais, beurre bio.',
      de: 'Algarve-Orangen, handwerkliches Weizenmehl, frische Waldpilze, Bio-Eier, cremiger Hüttenkäse, frische Kiwi, Bio-Butter.',
      it: 'Arance dell’Algarve, farina di grano artigianale, funghi freschi locali, uova biologiche, ricotta cremosa, kiwi freschi, burro biologico.',
    },
    nutrition: { calories: 580, protein: '16g', carbs: '72g', fat: '24g' },
    allergens: {
      pt: ['Glúten', 'Laticínios', 'Ovos'],
      en: ['Gluten', 'Dairy', 'Eggs'],
      es: ['Gluten', 'Lácteos', 'Huevos'],
      fr: ['Gluten', 'Produits laitiers', 'Œufs'],
      de: ['Gluten', 'Milchprodukte', 'Eier'],
      it: ['Glutine', 'Latticini', 'Uova'],
    },
    weight: '450g',
    deliveryTime: {
      pt: 'Entregue quente em 30-40 minutos no horário selecionado.',
      en: 'Delivered warm in 30-40 minutes at your selected time.',
      es: 'Entregado caliente en 30-40 minutos a la hora seleccionada.',
      fr: 'Livré chaud en 30-40 minutes à l’heure de votre choix.',
      de: 'Warm geliefert in 30-40 Minuten zum gewählten Zeitpunkt.',
      it: 'Consegnato caldo in 30-40 minuti all’ora selezionata.',
    },
    featured: true,
  },
  {
    id: 'menu-portuguese',
    name: {
      pt: 'Menu Português',
      en: 'Portuguese Menu',
      es: 'Menú Portugués',
      fr: 'Menu Portugais',
      de: 'Portugiesisches Menü',
      it: 'Menu Portoghese',
    },
    category: 'menu',
    price: 9.90,
    contents: {
      pt: ['Leite com chocolate tradicional', 'Pão de mistura rústico com presunto ibérico', 'Pastel de bacalhau crocante', 'Pastel de nata artesanal'],
      en: ['Traditional chocolate milk', 'Rustic mixed bread with premium Iberian ham', 'Crispy codfish cake', 'Artisanal Portuguese custard tart (Pastel de Nata)'],
      es: ['Leche con chocolate tradicional', 'Pan de mezcla rústico con jamón ibérico', 'Pastel de bacalao crujiente', 'Pastel de nata artesanal'],
      fr: ['Lait au chocolat traditionnel', 'Pain de campagne rustique au jambon ibérique', 'Beignet de morue croustillant', 'Pastel de nata artisanal'],
      de: ['Traditionelle Schokoladenmilch', 'Rustikales Mischbrot mit Premium-Iberico-Schinken', 'Knuspriges Stockfischbällchen (Pastel de Bacalhau)', 'Handgemachtes Pastel de Nata'],
      it: ['Latte al cioccolato tradizionale', 'Pane misto rustico con prosciutto iberico', 'Frittella di baccalà croccante', 'Pastel de nata artigianale'],
    },
    image: '/src/assets/images/portugues_menu_1784378730192.jpg',
    description: {
      pt: 'A essência da manhã lusitana. Desfrute dos sabores mais emblemáticos de Portugal com ingredientes tradicionais selecionados à mão.',
      en: 'The very essence of a Lusitanian morning. Taste the most iconic flavors of Portugal with hand-selected traditional ingredients.',
      es: 'La esencia de la mañana lusitana. Disfrute de los sabores más emblemáticos de Portugal con ingredientes tradicionales seleccionados a mano.',
      fr: 'L’essence même du matin lusitanien. Savourez les saveurs les plus emblématiques du Portugal avec des ingrédients traditionnels sélectionnés à la main.',
      de: 'Die Essenz eines portugiesischen Morgens. Genießen Sie die ikonischsten Aromen Portugals mit handverlesenen, traditionellen Zutaten.',
      it: 'L’essenza della colazione lusitana. Assapora i sapori più iconici del Portogallo con ingredienti tradizionali selezionati a mano.',
    },
    ingredients: {
      pt: 'Leite biológico, cacau português, trigo e centeio tradicionais, presunto curado de porco preto, bacalhau da Islândia, massa folhada crocante, creme de ovos e limão.',
      en: 'Organic milk, Portuguese cocoa, traditional wheat and rye, cured black pork ham, Atlantic cod, crispy puff pastry, egg custard cream.',
      es: 'Leche orgánica, cacao portugués, trigo y centeno tradicionales, jamón curado de cerdo negro, bacalao del Atlántico, hojaldre crujiente, crema de yema de huevo.',
      fr: 'Lait bio, cacao portugais, blé et seigle traditionnels, jambon de porc noir affiné, morue de l’Atlantique, pâte feuilletée croustillante, crème pâtissière aux œufs.',
      de: 'Bio-Milch, portugiesischer Kakao, traditionelles Weizen- und Roggenmehl, gereifter Schwarzschweinschinken, Kabeljau, knuspriger Blätterteig, Eigelbcreme.',
      it: 'Latte biologico, cacao portoghese, grano e segale tradizionali, prosciutto di maiale nero stagionato, baccalà dell’Atlantico, pasta sfoglia croccante, crema di uova.',
    },
    nutrition: { calories: 650, protein: '22g', carbs: '80g', fat: '26g' },
    allergens: {
      pt: ['Glúten', 'Laticínios', 'Ovos', 'Peixe'],
      en: ['Gluten', 'Dairy', 'Eggs', 'Fish'],
      es: ['Gluten', 'Lácteos', 'Huevos', 'Pescado'],
      fr: ['Gluten', 'Produits laitiers', 'Œufs', 'Poisson'],
      de: ['Gluten', 'Milchprodukte', 'Eier', 'Fisch'],
      it: ['Glutine', 'Latticini', 'Uova', 'Pesce'],
    },
    weight: '480g',
    deliveryTime: {
      pt: 'Pastel de bacalhau e pão entregues quentes no seu alojamento.',
      en: 'Codfish cake and bread delivered hot to your accommodation.',
      es: 'Pastel de bacalao y pan entregados calientes en su alojamiento.',
      fr: 'Beignet de morue et pain livrés chauds à votre hébergement.',
      de: 'Stockfischbällchen und Brot warm an Ihre Unterkunft geliefert.',
      it: 'Frittella di baccalà e pane consegnati caldi al tuo alloggio.',
    },
    popular: true,
  },
  {
    id: 'menu-brunch',
    name: {
      pt: 'Menu Brunch',
      en: 'Brunch Menu',
      es: 'Menú Brunch',
      fr: 'Menu Brunch',
      de: 'Brunch Menü',
      it: 'Menu Brunch',
    },
    category: 'menu',
    price: 15.90,
    contents: {
      pt: ['Sumo de laranja natural fresco', 'Ovos mexidos com farinheira tradicional', 'Mini tostadas artesanais', 'Rissol de camarão crocante', 'Rissol de leitão da Bairrada', 'Patê de sardinha tradicional português', 'Tarte caseira de maçã com canela'],
      en: ['Fresh squeezed orange juice', 'Scrambled eggs with traditional Farinheira sausage', 'Artisanal mini toasts', 'Crispy shrimp rissol (savory pastry)', 'Bairrada suckling pig rissol', 'Traditional Portuguese sardine pâté', 'Homemade warm apple pie with cinnamon'],
      es: ['Zumo de naranja natural fresco', 'Huevos revueltos con farinheira tradicional', 'Mini tostadas artesanales', 'Risol de camarón crujiente', 'Risol de cochinillo de Bairrada', 'Paté de sardina tradicional', 'Tarta casera de manzana con canela'],
      fr: ['Jus d’orange pressé frais', 'Œufs brouillés à la farinheira traditionnelle', 'Mini toasts artisanaux', 'Rissolé de crevettes croustillant', 'Rissolé de cochon de lait de Bairrada', 'Pâté de sardine portugais', 'Tarte aux pommes maison cannelle'],
      de: ['Frisch gepresster Orangensaft', 'Rührei mit traditioneller Farinheira-Wurst', 'Kleine handgemachte Toasts', 'Knuspriges Krabben-Rissol', 'Bairrada Spanferkel-Rissol', 'Traditionelle portugiesische Sardinenpaste', 'Hausgemachter warmer Apfelkuchen mit Zimt'],
      it: ['Spremuta d’arancia fresca', 'Uova strapazzate con farinheira tradizionale', 'Mini crostini artigianali', 'Rissol di gamberi croccante', 'Rissol di maialino da latte della Bairrada', 'Paté di sarde tradizionale', 'Torta di mele fatta in casa con cannella'],
    },
    image: '/src/assets/images/brunch_menu_1784378744904.jpg',
    description: {
      pt: 'O banquete definitivo. Um brunch completo que combina iguarias fumadas portuguesas e pastelaria artesanal fina. Perfeito para manhãs preguiçosas.',
      en: 'The ultimate feast. A comprehensive brunch combining Portuguese smoked delicacies and fine artisanal pastries. Ideal for lazy, luxurious mornings.',
      es: 'El banquete definitivo. Un brunch completo que combina embutidos portugueses ahumados y repostería artesanal fina. Perfecto para mañanas relajadas.',
      fr: 'Le festin ultime. Un brunch complet alliant charcuteries fumées portugaises et pâtisseries fines. Parfait pour les réveils en douceur.',
      de: 'Das ultimative Festmahl. Ein reichhaltiger Brunch, der portugiesische Räucherspezialitäten und feine handgemachte Backwaren vereint. Perfekt für entspannte Morgenstunden.',
      it: 'Il banchetto definitivo. Un brunch completo che unisce salumi affumicati portoghesi e raffinata pasticceria artigianale. Perfetto per mattine rilassanti.',
    },
    ingredients: {
      pt: 'Sumo de laranjas selecionadas, ovos biológicos, farinheira tradicional Alentejana, trigo selecionado, camarão selvagem, leitão da Bairrada, sardinhas portuguesas de conserva premium, maçãs de Alcobaça frescas, canela fina.',
      en: 'Selected oranges juice, organic eggs, traditional Alentejo farinheira, premium wheat, wild shrimp, Bairrada suckling pig, premium tinned sardines, fresh Alcobaça apples, fine cinnamon.',
      es: 'Zumo de naranjas seleccionadas, huevos orgánicos, farinheira tradicional del Alentejo, trigo premium, camarones silvestres, cochinillo de Bairrada, sardinas en conserva, manzanas frescas de Alcobaça, canela.',
      fr: 'Jus d’oranges sélectionnées, œufs bio, farinheira traditionnelle de l’Alentejo, blé premium, crevettes sauvages, cochon de lait de Bairrada, sardines de conserve premium, pommes d’Alcobaça, cannelle.',
      de: 'Ausgewählter Orangensaft, Bio-Eier, traditionelle Alentejo-Farinheira, Weizenmehl, Wildgarnelen, Spanferkel, Premium-Sardinen in der Dose, frische Alcobaça-Äpfel, Zimt.',
      it: 'Spremuta di arance selezionate, uova biologiche, farinheira tradizionale dell’Alentejo, grano pregiato, gamberi selvatici, maialino da latte, sarde in scatola, mele fresche, cannella.',
    },
    nutrition: { calories: 890, protein: '34g', carbs: '98g', fat: '38g' },
    allergens: {
      pt: ['Glúten', 'Laticínios', 'Ovos', 'Crustáceos', 'Peixe'],
      en: ['Gluten', 'Dairy', 'Eggs', 'Crustaceans', 'Fish'],
      es: ['Gluten', 'Lácteos', 'Huevos', 'Crustáceos', 'Pescado'],
      fr: ['Gluten', 'Produits laitiers', 'Œufs', 'Crustacés', 'Poisson'],
      de: ['Gluten', 'Milchprodukte', 'Eier', 'Krustentiere', 'Fisch'],
      it: ['Glutine', 'Latticini', 'Uova', 'Crostacei', 'Pesce'],
    },
    weight: '650g',
    deliveryTime: {
      pt: 'Ovos quentes e rissois estaladiços entregues em embalagem térmica de luxo.',
      en: 'Warm eggs and crispy rissóis delivered in luxury thermal packaging.',
      es: 'Huevos calientes y risoles crujientes entregados en embalajes térmicos de lujo.',
      fr: 'Œufs chauds et rissolés croustillants livrés dans un emballage thermique de luxe.',
      de: 'Warme Eier und knusprige Rissóis in einer luxuriösen Thermobox geliefert.',
      it: 'Uova calde e rissol croccanti consegnati in un imballaggio termico di lusso.',
    },
    featured: true,
  },
  {
    id: 'menu-summer',
    name: {
      pt: 'Cardápio de Verão',
      en: 'Summer Menu',
      es: 'Menú de Verano',
      fr: 'Menu d’Été',
      de: 'Sommermenü',
      it: 'Menu Estivo',
    },
    category: 'menu',
    price: 10.90,
    contents: {
      pt: ['Sumo de limão fresco e hortelã', 'Queijo fresco tradicional português', 'Torrada rústica com pasta de atum artesanal e alface gourmet', 'Torta de limão fresca e leve'],
      en: ['Fresh lemon and mint juice', 'Traditional fresh Portuguese soft cheese', 'Rustic toast with homemade tuna spread and gourmet lettuce', 'Light and fresh lemon tart'],
      es: ['Sumo de limón fresco con menta', 'Queso fresco tradicional portugués', 'Tostada rústica con pasta de atún artesanal y lechuga gourmet', 'Tarta de limón ligera y fresca'],
      fr: ['Citronnade fraîche et menthe', 'Fromage frais portugais traditionnel', 'Toast rustique tartiné de thon maison et salade gourmet', 'Tarte au citron fraîche et légère'],
      de: ['Frische Zitronen-Minz-Limonade', 'Traditioneller frischer portugiesischer Weichkäse', 'Rustikaler Toast mit hausgemachter Thunfischpaste und Gourmet-Salat', 'Leichte und frische Zitronentarte'],
      it: ['Succo di limone fresco e menta', 'Formaggio fresco tradizionale portoghese', 'Toast rustico con crema di tonno artigianale e lattuga gourmet', 'Crostata al limone fresca e leggera'],
    },
    image: '/src/assets/images/summer_menu_1784378759146.jpg',
    description: {
      pt: 'Fresco, leve e revigorante. Desenvolvido para os dias quentes de Lisboa, celebrando sabores mediterrânicos leves e sobremesas cítricas que despertam os sentidos.',
      en: 'Fresh, light, and invigorating. Created for hot Lisbon days, celebrating light Mediterranean flavors and citrusy pastries that awaken the senses.',
      es: 'Fresco, ligero y vigorizante. Diseñado para los días calurosos de Lisboa, celebrando sabores mediterráneos ligeros y repostería cítrica que despierta los sentidos.',
      fr: 'Frais, léger et vivifiant. Idéal pour les chaudes journées à Lisbonne, célébrant les saveurs méditerranéennes légères et des notes d’agrumes fraîches.',
      de: 'Frisch, leicht und belebend. Kreiert für die heißen Tage in Lissabon, feiert es leichte mediterrane Aromen und zitrische Nachspeisen.',
      it: 'Fresco, leggero e rinvigorente. Creato per le calde giornate di Lisbona, esalta i leggeri sapori mediterranei e i dolci agrumati che risvegliano i sensi.',
    },
    ingredients: {
      pt: 'Limões biológicos da Malveira, hortelã fresca do jardim, queijo fresco de cabra e vaca, pão de trigo rústico, atum em azeite premium, maionese artesanal, limas e limões de sobremesa.',
      en: 'Organic Malveira lemons, garden fresh mint, local soft cow & goat cheese, rustic wheat bread, tinned premium tuna in olive oil, homemade mayo, fresh limes.',
      es: 'Limones orgánicos de Malveira, menta fresca del jardín, queso fresco de cabra y vaca, pan de trigo rústico, atún premium en aceite de oliva, mayonesa artesanal.',
      fr: 'Citrons bio de Malveira, menthe fraîche du jardin, fromage frais de vache et chèvre, pain de blé rustique, thon de qualité à l’huile d’olive, citron vert.',
      de: 'Bio-Zitronen aus Malveira, frische Gartenminze, frischer Kuh- und Ziegenkäse, rustikales Weizenbrot, Premium-Thunfisch in Olivenöl, hausgemachte Mayonnaise.',
      it: 'Limoni biologici di Malveira, menta fresca, formaggio fresco di capra e mucca, pane rustico, tonno in olio d’oliva di alta qualità, maionese artigianale.',
    },
    nutrition: { calories: 490, protein: '18g', carbs: '62g', fat: '18g' },
    allergens: {
      pt: ['Glúten', 'Laticínios', 'Peixe'],
      en: ['Gluten', 'Dairy', 'Fish'],
      es: ['Gluten', 'Lácteos', 'Pescado'],
      fr: ['Gluten', 'Produits laitiers', 'Poisson'],
      de: ['Gluten', 'Milchprodukte', 'Fisch'],
      it: ['Glutine', 'Latticini', 'Pesce'],
    },
    weight: '420g',
    deliveryTime: {
      pt: 'Mantido refrigerado e fresco até à porta do seu hotel.',
      en: 'Kept chilled and fresh right to your hotel room.',
      es: 'Mantenido refrigerado y fresco hasta la puerta de su hotel.',
      fr: 'Conservé bien frais et livré directement à votre chambre d’hôtel.',
      de: 'Gut gekühlt direkt auf Ihr Hotelzimmer geliefert.',
      it: 'Mantenuto fresco e refrigerato direttamente alla tua camera d’hotel.',
    },
  },
  // EXTRAS
  {
    id: 'extra-bifana',
    name: {
      pt: 'Bifana Portuguesa',
      en: 'Portuguese Bifana',
      es: 'Bifana Portuguesa',
      fr: 'Bifana Portugaise',
      de: 'Portugiesische Bifana',
      it: 'Bifana Portoghese',
    },
    category: 'extra',
    price: 4.90,
    contents: { pt: ['Sandes de porco marinado tradicional em pão rústico de água'], en: ['Traditional marinated pork cutlet in a rustic bread roll'], es: ['Sándwich de cerdo marinado tradicional en pan de agua rústico'], fr: ['Sandwich de porc mariné traditionnel dans un pain croustillant'], de: ['Traditionelles mariniertes Schweineschnitzel im rustikalen Brötchen'], it: ['Panino con coppa di maiale marinata tradizionale in pane rustico'] },
    image: '/src/assets/images/bifana_portuguesa_gourmet_1784382526853.jpg',
    description: {
      pt: 'A lendária sandes de porco portuguesa. Carne de porco macia, marinada com alho, vinho branco e louro, cozinhada lentamente e servida quente num pão rústico com um toque de mostarda.',
      en: 'The legendary Portuguese pork sandwich. Tender pork loin marinated in white wine, garlic, and bay leaves, slow-cooked and served warm in a crusty roll with mustard.',
      es: 'El legendario sándwich de cerdo portugués. Lomo de cerdo tierno marinado en vino blanco, ajo y hojas de laurel, cocinado a fuego lento y servido caliente en pan rústico.',
      fr: 'Le légendaire sandwich de porc portugais. Échine de porc tendre marinée dans du vin blanc, ail et laurier, mijotée et servie chaude dans son pain maison.',
      de: 'Das legendäre portugiesische Schweineschnitzel-Brötchen. Zartes Schweinefleisch mariniert in Weißwein, Knoblauch und Lorbeerblättern, warm im knusprigen Brötchen serviert.',
      it: 'Il leggendario panino di maiale portoghese. Lonza di maiale tenerissima marinata in vino bianco, aglio e alloro, cotta lentamente e servita calda in un panino rustico.',
    },
    ingredients: { pt: 'Carne de lombo de porco premium, alho fresco, vinho branco de mesa, banha de porco, folha de louro, pão de água português tradicional, mostarda Dijon.', en: 'Premium pork loin, fresh garlic, white table wine, pork lard, bay leaf, traditional Portuguese water bread, Dijon mustard.' },
    nutrition: { calories: 380, protein: '24g', carbs: '42g', fat: '14g' },
    allergens: { pt: ['Glúten'], en: ['Gluten'] },
    weight: '180g',
    deliveryTime: { pt: 'Entregue bem quente.', en: 'Delivered piping hot.' },
  },
  {
    id: 'extra-prego',
    name: {
      pt: 'Prego no pão com picles',
      en: 'Steak Sandwich (Prego) with Pickles',
      es: 'Prego en pan con encurtidos',
      fr: 'Prego (Sandwich de bœuf) aux pickles',
      de: 'Rindersteak-Brötchen (Prego) mit Pickles',
      it: 'Prego nel pane con cetriolini',
    },
    category: 'extra',
    price: 4.90,
    contents: { pt: ['Bife do lombo de novilho em bolo do caco com manteiga de alho e picles caseiros'], en: ['Tender beef steak in a bolo do caco garlic bread with homemade pickles'], es: ['Bife de lomo de ternera en bolo do caco con mantequilla de ajo y encurtidos'], fr: ['Filet de bœuf tendre dans un pain bolo do caco au beurre d’ail et pickles'], de: ['Zartes Rindersteak im Bolo do Caco Knoblauchbrot mit hausgemachten Pickles'], it: ['Fettina di manzo in pane bolo do caco con burro all’aglio e cetriolini'] },
    image: '/src/assets/images/prego_no_pao_gourmet_1784382300174.jpg',
    description: {
      pt: 'Um clássico das cervejarias portuguesas. Bife de novilho extremamente tenro e sumarento, grelhado com alho e servido em bolo do caco quente com manteiga de ervas e picles crocantes.',
      en: 'A Portuguese tavern classic. Juicy, tender beef steak seared with garlic and served in warm traditional Madeira "Bolo do Caco" sweet potato bread with garlic butter.',
      es: 'Un clásico de las tabernas portuguesas. Filete de ternera jugoso y tierno, marcado con ajo y servido en bolo do caco templado con mantequilla aromática.',
      fr: 'Un classique des brasseries portugaises. Steak de bœuf juteux poêlé à l’ail et servi dans un pain traditionnel de Madère chaud au beurre persillé.',
      de: 'Ein absoluter Tavernen-Klassiker. Saftiges, zartes Rindersteak mit Knoblauch gebraten, serviert im warmen Bolo do Caco Knoblauchbrot.',
      it: 'Un classico delle taverne portoghesi. Fettina di manzo succosa scottata all’aglio, servita nel pane caldo bolo do caco con burro aromatizzato.',
    },
    ingredients: { pt: 'Carne de novilho tenra, alho, manteiga biológica, coentros e salsa, pão bolo do caco artesanal, picles artesanais de cenoura e pepino.', en: 'Tender beef steak, garlic, organic butter, parsley, artisanal bolo do caco bread, house pickles.' },
    nutrition: { calories: 420, protein: '28g', carbs: '44g', fat: '16g' },
    allergens: { pt: ['Glúten', 'Laticínios'], en: ['Gluten', 'Dairy'] },
    weight: '190g',
    deliveryTime: { pt: 'Grelhado no momento e entregue quente.', en: 'Freshly grilled and delivered hot.' },
  },
  {
    id: 'extra-croquete',
    name: {
      pt: 'Croquete de vitela',
      en: 'Veal Croquette',
      es: 'Croqueta de Ternera',
      fr: 'Croquette de Veau',
      de: 'Kalbshack-Krokette',
      it: 'Crocchetta di Vitello',
    },
    category: 'extra',
    price: 2.20,
    contents: { pt: ['Um croquete gourmet de vitela desfiada e frito na perfeição'], en: ['One gourmet shredded veal croquette fried to perfection'], es: ['Una croqueta gourmet de ternera desmenuzada crujiente'], fr: ['Une croquette de veau effiloché croustillante'], de: ['Eine Gourmet-Krokette aus gezupftem Kalbfleisch, knusprig frittiert'], it: ['Una crocchetta gourmet di vitello sfilacciato fritta alla perfezione'] },
    image: '/src/assets/images/croquete_de_vitela_gourmet_1784381878100.jpg',
    description: {
      pt: 'Crocante por fora, divinalmente cremoso por dentro. Elaborado com vitela de primeira qualidade cozinhada lentamente com vinho do Porto e ervas frescas.',
      en: 'Crispy on the outside, incredibly creamy on the inside. Made with premium slow-cooked veal shredded with a touch of Port wine and fresh herbs.',
      es: 'Crujiente por fuera, extremadamente cremosa por dentro. Elaborada con ternera premium cocinada a fuego lento con vino de Oporto.',
      fr: 'Croustillante à l’extérieur, onctueuse à l’intérieur. Confectionnée avec du veau effiloché mijoté avec un soupçon de vin de Porto.',
      de: 'Außen knusprig, innen cremig. Hergestellt aus langsam gegartem Kalbfleisch mit einem Schuss Portwein und feinen Kräutern.',
      it: 'Croccante fuori, cremosissima dentro. Preparata con vitello di prima scelta cotto a fuoco lento con vino di Porto e aromi freschi.',
    },
    ingredients: { pt: 'Carne de vitela nacional, caldo caseiro de carne, vinho do Porto, farinha de trigo, ovos, pão ralado crocante panko.', en: 'Portuguese veal, rich beef broth, Port wine, flour, eggs, golden panko breadcrumbs.' },
    nutrition: { calories: 150, protein: '8g', carbs: '12g', fat: '7g' },
    allergens: { pt: ['Glúten', 'Ovos', 'Laticínios'], en: ['Gluten', 'Eggs', 'Dairy'] },
    weight: '60g',
    deliveryTime: { pt: 'Entregue bem estaladiço.', en: 'Delivered extra crispy.' },
  },
  {
    id: 'extra-rissol-leitao',
    name: {
      pt: 'Rissol de Leitão',
      en: 'Suckling Pig Rissol',
      es: 'Risol de Cochinillo',
      fr: 'Rissolé de Cochon de Lait',
      de: 'Spanferkel-Rissol',
      it: 'Rissol di Maialino',
    },
    category: 'extra',
    price: 3.90,
    contents: { pt: ['Rissol tradicional de massa artesanal recheado com leitão da Bairrada assado'], en: ['Traditional savory pastry filled with roasted Bairrada suckling pig'], es: ['Risol tradicional relleno de cochinillo asado al estilo de Bairrada'], fr: ['Rissolé traditionnel garni de cochon de lait rôti de Bairrada'], de: ['Klassische Teigtasche gefüllt mit gebratenem Bairrada-Spanferkel'], it: ['Rissol tradizionale ripieno di maialino arrosto della Bairrada'] },
    image: '/src/assets/images/rissol_de_leitao_gourmet_1784382021885.jpg',
    description: {
      pt: 'Uma iguaria premium. Massa caseira delicada recheada com leitão assado desfiado da Bairrada e um molho cremoso condimentado com pimenta preta.',
      en: 'A premium delicacy. Delicate homemade pastry filled with rich, shredded roasted Bairrada suckling pig and a creamy black pepper sauce.',
      es: 'Una exquisitez premium. Masa delicada rellena con cochinillo desmenuzado y una salsa cremosa de pimienta negra.',
      fr: 'Une délicatesse haut de gamme. Pâte fine maison farcie de cochon de lait de Bairrada rôti et d’une sauce veloutée poivrée.',
      de: 'Eine erlesene Spezialität. Feiner Teig gefüllt mit saftigem gezupftem Spanferkel und pfeffriger Cremesauce.',
      it: 'Una delizia raffinata. Sfoglia fatta a mano ripiena di maialino arrosto sfilacciato e salsa vellutata al pepe nero.',
    },
    ingredients: { pt: 'Leitão assado da Bairrada, pimenta preta, alho, gordura de leitão, leite, farinha, pão ralado.', en: 'Bairrada roasted pig, black pepper, garlic, pig fat, milk, flour, breadcrumbs.' },
    nutrition: { calories: 210, protein: '11g', carbs: '18g', fat: '10g' },
    allergens: { pt: ['Glúten', 'Laticínios', 'Ovos'], en: ['Gluten', 'Dairy', 'Eggs'] },
    weight: '80g',
    deliveryTime: { pt: 'Mantido quente e crocante.', en: 'Delivered warm and crispy.' },
  },
  {
    id: 'extra-pastel-nata',
    name: {
      pt: 'Pastel de nata',
      en: 'Pastel de Nata',
      es: 'Pastel de Nata',
      fr: 'Pastel de Nata',
      de: 'Pastel de Nata',
      it: 'Pastel de Nata',
    },
    category: 'extra',
    price: 1.80,
    contents: { pt: ['O autêntico pastel de nata português com açúcar e canela à parte'], en: ['The authentic Portuguese custard tart with sugar and cinnamon on the side'], es: ['El auténtico pastel de nata portugués con azúcar y canela'], fr: ['Le véritable pastel de nata portugais servi avec cannelle et sucre'], de: ['Der authentische portugiesische Blätterteigpudding mit Zimt'], it: ['L’autentico pasticcino portoghese alla crema con cannella e zucchero'] },
    image: 'https://images.unsplash.com/photo-1511018556340-d16986a1c194?q=80&w=600&auto=format&fit=crop',
    description: {
      pt: 'O doce mais famoso de Portugal. Fabricado artesanalmente por pasteleiros experientes com uma massa folhada ultra-estaladiça e recheio cremoso perfeitamente caramelizado.',
      en: 'Portugal’s most iconic sweet pastry. Hand-crafted by master bakers with ultra-crispy puff pastry and a rich, perfectly caramelized egg custard cream.',
      es: 'La pastelería más famosa de Portugal. Elaborada artesanalmente con hojaldre crujiente y crema horneada y caramelizada.',
      fr: 'La pâtisserie la plus célèbre du Portugal. Fabriquée de manière artisanale avec une pâte feuilletée croustillante et une crème dorée au four.',
      de: 'Das berühmteste Gebäck Portugals. Handgemacht mit ultra-knusprigem Blätterteig und perfekt karamellisierter Puddingcreme.',
      it: 'La sfoglia dolce più famosa del Portogallo. Preparata artigianalmente con sfoglia croccante e un ripieno cremoso caramellato in superficie.',
    },
    ingredients: { pt: 'Farinha de trigo, açúcar fino, gemas de ovos biológicos, limão fresco, pau de canela, leite gordo, manteiga biológica.', en: 'Wheat flour, fine sugar, organic egg yolks, fresh lemon peel, cinnamon stick, whole milk.' },
    nutrition: { calories: 240, protein: '4g', carbs: '32g', fat: '10g' },
    allergens: { pt: ['Glúten', 'Laticínios', 'Ovos'], en: ['Gluten', 'Dairy', 'Eggs'] },
    weight: '75g',
    deliveryTime: { pt: 'Fresco do forno e crocante.', en: 'Fresh out of the oven and crispy.' },
  },
  {
    id: 'extra-pastel-bacalhau',
    name: {
      pt: 'Pastel de bacalhau',
      en: 'Codfish Cake (Pastel de Bacalhau)',
      es: 'Pastel de Bacalao',
      fr: 'Beignet de Morue',
      de: 'Stockfischbällchen',
      it: 'Frittella di Baccalà',
    },
    category: 'extra',
    price: 1.90,
    contents: { pt: ['Bolinho tradicional de bacalhau artesanal frito na hora'], en: ['Traditional codfish cake made with Atlantic cod fried golden'], es: ['Bolito de bacalao tradicional frito al momento'], fr: ['Beignet de morue traditionnel doré et croustillant'], de: ['Klassisches Kabeljau-Krokettchen, golden frittiert'], it: ['Frittella tradizionale di baccalà fritto al momento'] },
    image: '/src/assets/images/pastel_de_bacalhau_gourmet_1784382159500.jpg',
    description: {
      pt: 'Feito com bacalhau do Atlântico de cura tradicional desfiado, misturado com batatas cozidas, ovos biológicos, cebolas e salsa picada, frito até dourar.',
      en: 'Made with premium salted Atlantic cod, mashed potatoes, organic eggs, finely chopped onions, and fresh parsley, fried until golden and crisp.',
      es: 'Elaborado con bacalao de curado tradicional, patatas, huevos orgánicos, cebolla y perejil fresco, frito hasta quedar crujiente.',
      fr: 'Préparé avec de la morue séchée de qualité, purée de pommes de terre, œufs bio, oignon et persil frais.',
      de: 'Aus feinstem gesalzenem Kabeljau, Kartoffeln, Zwiebeln und viel frischer Petersilie geformt und goldbraun frittiert.',
      it: 'Preparato con baccalà dissalato, patate, uova, cipolla e prezzemolo fresco, fritto fino a ottenere una crosticina dorata.',
    },
    ingredients: { pt: 'Bacalhau curado, batatas selecionadas, ovos biológicos, azeite, cebola fresca, salsa picada.', en: 'Atlantic cod, potatoes, organic eggs, olive oil, fresh onions, parsley.' },
    nutrition: { calories: 120, protein: '9g', carbs: '11g', fat: '4g' },
    allergens: { pt: ['Peixe', 'Ovos'], en: ['Fish', 'Eggs'] },
    weight: '70g',
    deliveryTime: { pt: 'Entregue crocante e morno.', en: 'Delivered crispy and warm.' },
  },
  {
    id: 'extra-cocacola',
    name: { pt: 'Coca-Cola', en: 'Coca-Cola', es: 'Coca-Cola', fr: 'Coca-Cola', de: 'Coca-Cola', it: 'Coca-Cola' },
    category: 'extra',
    price: 1.90,
    contents: { pt: ['Lata de Coca-Cola original fresca 330ml'], en: ['Chilled original Coca-Cola can 330ml'] },
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=600&auto=format&fit=crop',
    description: { pt: 'Refrigerante clássico bem fresco.', en: 'Classic chilled soda.' },
    ingredients: { pt: 'Água gaseificada, açúcar, extrato de cola, cafeína.', en: 'Carbonated water, sugar, cola extract, caffeine.' },
    nutrition: { calories: 139, protein: '0g', carbs: '35g', fat: '0g' },
    allergens: { pt: [], en: [] },
    weight: '330ml',
    deliveryTime: { pt: 'Entregue bem frio.', en: 'Delivered ice-cold.' },
  },
  {
    id: 'extra-fanta',
    name: { pt: 'Fanta Laranja', en: 'Fanta Orange', es: 'Fanta Naranja', fr: 'Fanta Orange', de: 'Fanta Orange', it: 'Fanta Arancia' },
    category: 'extra',
    price: 1.90,
    contents: { pt: ['Lata de Fanta Laranja refrescante 330ml'], en: ['Chilled refreshing Fanta Orange can 330ml'] },
    image: 'https://images.unsplash.com/photo-1624552184280-9e9631bbeee9?q=80&w=600&auto=format&fit=crop',
    description: { pt: 'Refresco com sabor a laranja sumarenta.', en: 'Sassy orange flavor beverage.' },
    ingredients: { pt: 'Água gaseificada, sumo de laranja de concentrado, açúcar.', en: 'Carbonated water, orange juice from concentrate, sugar.' },
    nutrition: { calories: 110, protein: '0g', carbs: '28g', fat: '0g' },
    allergens: { pt: [], en: [] },
    weight: '330ml',
    deliveryTime: { pt: 'Entregue bem frio.', en: 'Delivered ice-cold.' },
  },
  {
    id: 'extra-agua',
    name: { pt: 'Água Mineral', en: 'Mineral Water', es: 'Agua Mineral', fr: 'Eau Minérale', de: 'Mineralwasser', it: 'Acqua Minerale' },
    category: 'extra',
    price: 1.50,
    contents: { pt: ['Garrafa de água mineral natural premium 500ml'], en: ['Premium Portuguese natural mineral water bottle 500ml'] },
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?q=80&w=600&auto=format&fit=crop',
    description: { pt: 'Água mineral natural pura proveniente de nascentes portuguesas preservadas.', en: 'Pure natural mineral water from pristine Portuguese mountain springs.' },
    ingredients: { pt: 'Água mineral natural enriquecida com minerais essenciais.', en: 'Natural mineral water with essential minerals.' },
    nutrition: { calories: 0, protein: '0g', carbs: '0g', fat: '0g' },
    allergens: { pt: [], en: [] },
    weight: '500ml',
    deliveryTime: { pt: 'Entregue fresca.', en: 'Delivered fresh and cool.' },
  }
];

export const PROMOTION_CARDS = [
  {
    id: 'promo-5plus1',
    badge: { pt: 'PROMOÇÃO', en: 'PROMOTION', es: 'PROMOCIÓN', fr: 'PROMOTION', de: 'AKTION', it: 'OFFERTA' },
    title: {
      pt: 'Compre 5 menus, receba 1 extra grátis',
      en: 'Buy 5 menus, get 1 extra free',
      es: 'Compre 5 menús, reciba 1 extra gratis',
      fr: 'Achetez 5 menus, recevez 1 supplément gratuit',
      de: 'Kaufe 5 Menüs, erhalte 1 Extra gratis',
      it: 'Acquista 5 menu, ricevi 1 extra gratis',
    },
    description: {
      pt: 'Ideal para grupos ou famílias. Ao encomendar 5 menus principais, adicione o extra que mais deseja inteiramente de oferta.',
      en: 'Perfect for groups or families. Order 5 main menus and add any extra of your choice entirely for free.',
      es: 'Ideal para grupos o familias. Al pedir 5 menús, añada el extra que prefiera totalmente gratis.',
      fr: 'Idéal pour les groupes. Commandez 5 menus principaux et ajoutez le supplément de votre choix offert.',
      de: 'Ideal für Gruppen oder Familien. Bestellen Sie 5 Hauptmenüs und erhalten Sie ein Extra Ihrer Wahl gratis.',
      it: 'Ideale per gruppi o famiglie. Ordina 5 menu principali e aggiungi un extra a tua scelta in regalo.',
    },
    tag: '5PLUS1',
  },
  {
    id: 'promo-earlybird',
    badge: { pt: 'MADRUGADOR', en: 'EARLY BIRD', es: 'MADRUGADOR', fr: 'LÈVE-TÔT', de: 'FRÜHAUFSTEHER', it: 'EARLY BIRD' },
    title: {
      pt: 'Desconto Madrugador para entregas antes das 09h',
      en: 'Early Bird discount for deliveries before 09:00 AM',
      es: 'Descuento Madrugador para entregas antes de las 09h00',
      fr: 'Réduction Lève-Tôt pour les livraisons avant 09h00',
      de: 'Frühaufsteher-Rabatt für Lieferungen vor 09:00 Uhr',
      it: 'Sconto Early Bird per consegne prima delle 09:00',
    },
    description: {
      pt: 'Comece o dia mais cedo e poupe. Agende a sua entrega para qualquer horário entre as 08:00 e as 09:00 e ganhe 10% de desconto automático com o código EARLYBIRD.',
      en: 'Start your day early and save. Schedule your delivery between 08:00 AM and 09:00 AM and get a 10% discount automatically with code EARLYBIRD.',
      es: 'Comience su día temprano y ahorre. Programe su entrega entre las 08h00 y las 09h00 y obtenga un 10% de descuento automático con el código EARLYBIRD.',
      fr: 'Commencez la journée plus tôt et économisez. Planifiez votre livraison entre 08h00 et 09h00 et profitez de 10% de réduction automatique avec le code EARLYBIRD.',
      de: 'Starten Sie früh in den Tag und sparen Sie. Planen Sie Ihre Lieferung vor 09:00 Uhr und erhalten Sie 10% Rabatt mit dem Code EARLYBIRD.',
      it: 'Inizia la giornata in anticipo e risparmia. Programma la tua consegna tra le 08:00 e le 09:00 e ricevi il 10% di sconto automatico con il codice EARLYBIRD.',
    },
    tag: 'EARLYBIRD',
  },
];

export const DELIVERY_ZONES = [
  { name: 'Penha de França', zipPrefixes: ['1170', '1900'] },
  { name: 'Graça', zipPrefixes: ['1170'] },
  { name: 'São Vicente', zipPrefixes: ['1100', '1170'] },
  { name: 'Alfama', zipPrefixes: ['1100'] },
  { name: 'Santa Clara', zipPrefixes: ['1750'] },
  { name: 'Arroios', zipPrefixes: ['1150', '1170'] },
  { name: 'Santa Apolónia', zipPrefixes: ['1100', '1900'] },
];

export const AVAILABLE_HOURS = [
  '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00', '13:30'
];

export const FAQS = [
  {
    q: {
      pt: 'Como funcionam as entregas silenciosas?',
      en: 'How do silent deliveries work?',
      es: '¿Cómo funcionan las entregas silenciosas?',
      fr: 'Comment fonctionnent les livraisons silencieuses?',
      de: 'Wie funktionieren die stillen Lieferungen?',
      it: 'Come funzionano le consegne silenziose?',
    },
    a: {
      pt: 'Respeitamos as suas manhãs. Os nossos estafetas são instruídos a não tocar à campainha e a entregar o pequeno-almoço silenciosamente à porta do seu quarto ou apartamento, ou conforme as instruções dadas.',
      en: 'We respect your mornings. Our couriers are trained to deliver silently to your door or room without ringing bells, following your specific instructions.',
      es: 'Respetamos sus mañanas. Nuestros repartidores no tocarán el timbre y dejarán su desayuno silenciosamente en la puerta de su habitación o según sus instrucciones.',
      fr: 'Nous respectons vos matinées. Nos livreurs ont pour instruction de ne pas sonner et de déposer le panier de petit-déjeuner silencieusement à votre porte.',
      de: 'Wir respektieren Ihren Morgen. Unsere Kuriere sind angewiesen, nicht zu klingeln und Ihr Frühstück lautlos vor die Zimmertür oder gemäß Ihren Anweisungen zu liefern.',
      it: 'Rispettiamo le tue mattine. I nostri corrieri sono istruiti a non suonare il campanello e a lasciare la colazione silenziosamente alla tua porta.',
    }
  },
  {
    q: {
      pt: 'Até que horas posso fazer a minha reserva para o dia seguinte?',
      en: 'Until what time can I order for the next day?',
      es: '¿Hasta qué hora puedo pedir para el día siguiente?',
      fr: 'Jusqu’à quelle heure puis-je commander pour le lendemain?',
      de: 'Bis zu welcher Uhrzeit kann ich für den nächsten Tag bestellen?',
      it: 'Fino a che ora posso ordinare per il giorno successivo?',
    },
    a: {
      pt: 'Para garantir a máxima frescura dos nossos produtos artesanais, as encomendas para o dia seguinte devem ser feitas até às 23:00. Após este horário, o sistema bloqueia automaticamente o dia seguinte.',
      en: 'To ensure maximum freshness of our artisanal goods, orders for the next day must be placed by 11:00 PM (23:00). After this hour, the next day is automatically blocked.',
      es: 'Para garantizar la frescura de nuestros productos artesanales, los pedidos deben realizarse antes de las 23h00 del día anterior. Después de esa hora, se bloquea el día siguiente.',
      fr: 'Pour garantir la fraîcheur de nos produits artisanaux, les commandes doivent être passées avant 23h00 le soir précédent. Passé ce délai, le jour suivant est bloqué.',
      de: 'Um maximale Frische zu gewährleisten, müssen Bestellungen bis 23:00 Uhr des Vorabends aufgegeben werden. Danach wird der Folgetag automatisch blockiert.',
      it: 'Per garantire la massima freschezza dei nostri prodotti artigianali, gli ordini per il giorno successivo devono essere effettuati entro le 23:00.',
    }
  },
  {
    q: {
      pt: 'Como posso validar se entregam no meu endereço?',
      en: 'How do I check if you deliver to my address?',
      es: '¿Cómo compruebo si entregan en mi dirección?',
      fr: 'Comment savoir si vous livrez à mon adresse?',
      de: 'Wie prüfe ich, ob Sie an meine Adresse liefern?',
      it: 'Come posso verificare se consegnate al mio indirizzo?',
    },
    a: {
      pt: 'Durante a reserva, ao introduzir o seu código postal ou bairro histórico, o nosso sistema valida instantaneamente se está nas nossas áreas exclusivas de Lisboa (Alfama, Graça, Arroios, etc.) antes de prosseguir com o pagamento.',
      en: 'During booking, once you enter your zip code or historic neighborhood, our system instantly validates if it falls under our exclusive Lisbon delivery zones before checkout.',
      es: 'Al introducir su código postal o barrio histórico en la reserva, el sistema valida instantáneamente si está dentro de nuestras áreas de Lisboa.',
      fr: 'Lors de la réservation, en saisissant votre code postal ou quartier historique, notre système valide instantanément si vous êtes dans nos zones de Lisbonne.',
      de: 'Geben Sie einfach Ihre Postleitzahl oder Ihr Viertel bei der Buchung ein. Das System prüft sofort, ob es in unseren exklusiven Liefergebieten in Lissabon liegt.',
      it: 'Durante la prenotazione, inserendo il tuo codice postale o il quartiere storico, il sistema verificherà all’istante se si trova nelle nostre aree di consegna.',
    }
  }
];
